---
## Message Queue ##

  - name: Installing Message queue (Ubuntu)
    apt:
      name:
        - rabbitmq-server
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Adding the openstack user (Ubuntu)
    community.rabbitmq.rabbitmq_user:
      user: openstack
      password: RABBIT_PASS
      vhost: /
      configure_priv: .*
      read_priv: .*
      write_priv: .*
      state: present
    when: ansible_distribution == "Ubuntu"
